# Tensor Flow basics

## Introduction to Tensorflow

In [22]:
import pandas as pd 
import tensorflow as tf 
import logging
import numpy as np

In [2]:
logger = logging.getLogger()
logging.basicConfig(format='%(levelname)s:%(message)s', level=logging.INFO)

### Tensor Dimension

In [8]:
# zero dimension: scalar
d0 = tf.ones((1,))
d0

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [9]:
# one dimesion: like a list 
d1 = tf.ones((3,))
d1

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [12]:
# two dimention: like a matrix
d2 = tf.ones((3, 5))
d2


<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [37]:
tf.ones([3,5])

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [11]:
# three dimention
d3 = tf.ones((2,2,2))
print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


### Tensor Constant

In [17]:
from tensorflow import constant

In [19]:
c1 = constant(3, shape= [2,3])
c1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3]])>

In [36]:
constant(3, shape= (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3]])>

In [21]:
c2 = constant([1,2,3,4,5,6], shape=[2, 3])
c2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [28]:
a_np = np.arange(6).reshape(2, 3)
print(a_np)
c3 = constant(a_np)
print(c3)

[[0 1 2]
 [3 4 5]]
tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [31]:
# matrix transpose: row => column, column => row
b_np = np.arange(12).reshape(3,4)
print(b_np)
print(b_np.transpose())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [33]:
tf.zeros_like(b_np)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

In [34]:
tf.zeros_like(c3)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

In [35]:
tf.fill([3,3], 7)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])>

### Variables
- dtype should match each other to calcualte tensors

In [40]:
# a variable of 4 elements with initial value setting
a0 = tf.Variable([1,2,3,4], dtype=tf.float16)
a1 = tf.Variable([1,2,3,4], dtype=tf.int16)
print(a0)
print(a1)

<tf.Variable 'Variable:0' shape=(4,) dtype=float16, numpy=array([1., 2., 3., 4.], dtype=float16)>
<tf.Variable 'Variable:0' shape=(4,) dtype=int16, numpy=array([1, 2, 3, 4], dtype=int16)>


In [64]:
c0 = tf.constant(value=[2], shape=[1],dtype=tf.float16)
c1 = tf.constant([3],dtype=tf.int16)
c2 = tf.constant([5],dtype=tf.int16)
print(c0)
print(c1)
print(c2)

tf.Tensor([2.], shape=(1,), dtype=float16)
tf.Tensor([3], shape=(1,), dtype=int16)
tf.Tensor([5], shape=(1,), dtype=int16)


In [51]:
tf.multiply(x=a0, y=c0)

<tf.Tensor: shape=(4,), dtype=float16, numpy=array([2., 4., 6., 8.], dtype=float16)>

In [55]:
tf.multiply(a1,c1)

<tf.Tensor: shape=(4,), dtype=int16, numpy=array([ 3,  6,  9, 12], dtype=int16)>

In [57]:
a1*c1

<tf.Tensor: shape=(4,), dtype=int16, numpy=array([ 3,  6,  9, 12], dtype=int16)>

In [58]:
a1 + c1

<tf.Tensor: shape=(4,), dtype=int16, numpy=array([4, 5, 6, 7], dtype=int16)>

In [74]:
# adding multiple tensors to the calculatoin method doesn't work!!!!
print(tf.add(a1,c1,c2))
print(tf.add(tf.add(a1,c1),c2))

tf.Tensor([4 5 6 7], shape=(4,), dtype=int16)
tf.Tensor([ 9 10 11 12], shape=(4,), dtype=int16)


In [73]:
# this method work when calculate multiple tensors
print(a1+c1+c2)
print(a1*c1)
print(a1*c1+c2)

tf.Tensor([ 9 10 11 12], shape=(4,), dtype=int16)
tf.Tensor([ 3  6  9 12], shape=(4,), dtype=int16)
tf.Tensor([ 8 11 14 17], shape=(4,), dtype=int16)


### Basic Operations - Matrix calculation
1. tf.add(), tf.multiply()   
- the shapes should be same between two from right to the left of the dimensions.
A(shape) 
A1 x A2432 => shape(2,4,3,2)  
A2 x A2432 => shape(2,4,3,2)  
A32 x A2432 => shape(2,4,3,2)  
A432 x A2432 => shape(2,4,3,2)  
A2432 x A2432 => shape(2,4,3,2)  

For example:  
[1,2] x [3, 4] = [3, 8]  
[3] x [1, 2] = [3, 6]  
[1,2] x [[1,2], [3,4]] = [[1,4], [3,8]]  

2. tf.matmul()  
- column shape of the left tesor should be same wit the row shape of the right tensor
A23 dot A35 => shape([2, 5])
(calculated tensor unit: 23, 35)
A243 dot A34 => shape([2,4,4])
(calculated tensor unit: two 43 dot one 34 => two 44)
A435 dot A453 => shape[(4,3,3])
(calculated tensor unit: four 35 dot four 53 => four 33)
A2435 dot A53 => shape[(2,4,3,3])
(calculated tensor unit: twoxfour 35 dot one 53 => twoxfour 33)
A2435 dot A453 => shape([2, 4, 3, 3])
(calculated tensor unit: twoxfour 35 dot four 53 => twoxfour 33)
([4,3,5] dot [5,3] => [4,3,3] )

A34 dot A543 => shape([5,3,3])
(calculated tensor unit: one 34 dot five 43 => five 33)

NOTE: 
- dot product requires both tensor should have 2 dimension matrix minimum. 


 

In [149]:
A34=tf.ones([3,4])
A543=tf.ones([5,4,3])
tf.matmul(A34, A543).shape

TensorShape([5, 3, 3])

In [150]:
A23=tf.constant(np.arange(6), shape=[2,3])
A23

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]])>

In [ ]:
try:
    temp = tf.multiply(A432, A2432)
    temp.shape
    print(temp)
except:
    print("Calculation Error")

tf.Tensor(
[[[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]], shape=(2, 4, 3, 2), dtype=float32)


In [83]:
a0=tf.constant([1])
b0=tf.constant([2])
a1=tf.constant([1,2])
b1=tf.constant([3,4])
a2=tf.constant([[1,2],[3,4]])
b2=tf.constant([[5,6],[7,8]])

print(tf.add(a0, b0))
print(tf.add(a0, b1))
print(tf.add(a1, a2))
print(tf.add(a2, b2))
print(tf.add(a0, b2))

tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([4 5], shape=(2,), dtype=int32)
tf.Tensor(
[[2 4]
 [4 6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[6 7]
 [8 9]], shape=(2, 2), dtype=int32)


In [89]:
c1=tf.constant([10,10,10])
d1=tf.constant(np.arange(6).reshape(3,2))
print(c1)
print(d1)
try:
    print(tf.add(c1, a1))
except:
    print("Calculation Error")

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[0 1]
 [2 3]
 [4 5]], shape=(3, 2), dtype=int32)
Calculation Error


In [97]:
print(a1)
print(a2)
try:
    print(tf.multiply(a1, a2))
except:
    print("Calculation Error")

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 4]
 [3 8]], shape=(2, 2), dtype=int32)


In [133]:
A0 = tf.ones([1])
A14 = tf.ones([1,4])
A241 = tf.ones([2, 1,4])
A24 = tf.ones([2,4])
A32 = tf.ones([3,2])
A34 = tf.ones([3,4])
A43 = tf.ones([4,3])
A432=tf.ones([4,3,2])
A232 = tf.ones([2,3,2])
A2432 = tf.ones([2,4,3,2])


In [132]:
try:
    temp = tf.multiply(A432, A2432)
    temp.shape
    print(temp)
except:
    print("Calculation Error")

tf.Tensor(
[[[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]], shape=(2, 4, 3, 2), dtype=float32)


In [134]:
try:
    temp = tf.matmul(A14, A43)
    temp.shape
    print(temp)
except:
    print("Calculation Error")

tf.Tensor([[4. 4. 4.]], shape=(1, 3), dtype=float32)


In [135]:
A24=tf.ones([2,4])
A43=tf.ones([4,3])
tf.matmul(A24,A43)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4., 4., 4.],
       [4., 4., 4.]], dtype=float32)>

In [144]:
A243=tf.ones([2,4,3])
A34=tf.ones([3,4])
print(tf.matmul(A243, A34))


tf.Tensor(
[[[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]], shape=(2, 4, 4), dtype=float32)


In [148]:
A435=tf.ones([4,3,5])
A453=tf.ones([4, 5,3])
 
tf.matmul(A435,A453).shape

TensorShape([4, 3, 3])

### Basic Operations - Reducing tensor dimensions
reduce_all()
reduce_any()
reduce_logsumexp()
reduce_pro()
reduce_max()
reduce_min()
reduce_mean()

A234=tf.ones([2,3,4])  
tf.reduce_sum(A234) => 24  
tf.reduce_sum(A234,axis=0) => shape=(3, 4)  
tf.reduce_sum(A234,axis=1) => shape=(2, 4)  

In [154]:
A234=tf.ones([2,3,4])
tf.reduce_sum(A234,axis=1)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]], dtype=float32)>

### Advanced Operations
- gradient()
- reshape()
- random()

#### find an optimal value of y=x^2

In [15]:
import tensorflow as tf

In [ ]:

# define variable x
x = tf.Variable(initial_value=-1.0)

# define y within instance of gradientTape
# What is GradientTape ():
# GradientTape is a mathematical tool for automatic differentiation (autodiff), which is the core functionality of TensorFlow. It does not "track" the autodiff, it is a key part of performing the autodiff.Dec
# Computes the gradient using operations recorded in context of this tape. Note: Unless you set persistent=True a GradientTape can only be used to compute one set of gradients (or jacobians). ... a list of gradients, one for each element of target.
# with tf.GradientTape(persistent=False, watch_accessed_variables=True) as tape:
with tf.GradientTape(persistent=False, watch_accessed_variables=False) as tape:
    # NOTE: if watch_accessed_variables=False then should define tape.watch(variable). If it is True, no need to define watch of the variable.
    tape.watch(x)
    y=tf.multiply(x,x)

In [181]:
# evaluate the gradient of y at x=-1
g = tape.gradient(target=y, sources=x)
print(g.numpy())

-2.0


In [17]:
def compute_gradient(x0):
    """ x0: inital value of variable x"""
    x =tf.Variable(x0)
    
    with tf.GradientTape() as tape:
        tape.watch(x)
        # define y
        y = tf.multiply(x=x, y=x)
        
    return tape.gradient(y, x).numpy()

In [19]:
print(compute_gradient(x0=-1.0))
print(compute_gradient(x0=1.0))
print(compute_gradient(x0=0.0))

-2.0
2.0
0.0


#### Reshape a grayscale image

In [11]:
import tensorflow as tf

# generate grayscale image
gray = tf.random.uniform(shape=[2,2], maxval=255, dtype=tf.int32)

print(gray.numpy())

[[ 15 227]
 [ 86 242]]


In [20]:
# reshape grayscale image
gray = tf.reshape(tensor=gray, shape=[2*2,1])
print(gray.numpy())
print(tf.reduce_sum(gray).numpy())

[[ 15]
 [227]
 [ 86]
 [242]]
570


## Linear models

### Input data

### Loss functions

### Linear regression

### Batch training